- heading: '参加者に発言させる'
  scenes:
    - scene: '最初の発言が少ない場合'
      phrases:
        - '◯◯◯の課題について意見を思いついた方は述べてください。'
        - '◯◯◯の目標・将来像について意見を思いついた方は述べてください。'
    - scene: '発言に対する意見が少ない場合'
      phrases:
        - '何か考えがある方は述べてください。'
    - scene: '発言が少ない場合'
      phrases:
        - 'システム上での議論ということで緊張されている方もいらっしゃるかもしれませんが、発言の良し悪しは関係あません.どしどし発言してください。'
    - scene: 'システムの有効活用を促す場合'
      phrases:
        - '「論点タグ」を追加して意見を投稿するようにしてください。'
        - '「論点タグ」をクリックするとテーマをしぼった議論を閲覧することができます。'
        - '「キーワード」には発言で多く見られた言葉が表示されます。議論の参考にして下さい。'
    - scene: 'デザイン案を引き出す場合'
      phrases:
        - 'コンセプトを踏まえて、スケッチなどデザイン案を東欧してください。'
    - scene: 'デザイン案が少ない場合'
      phrases:
        - '絵のうまい下手は関係ありません。どしどし投稿してください。'
- heading: '意見を掘り下げる'
  scenes:
    - scene: '発言の説明が不十分な場合'
      phrases:
        - '具体的に説明してください。'
        - '何か例を挙げてください。'
    - scene: '新たな観点からの発言を求めたい場合'
      phrases:
        - '違う意見のある方は述べてください。'
    - scene: '議論に対する理解度を把握したい場合'
      phrases:
        - '今までの議論で何か引っかかっているところや疑問などがある方はいませんか？'
    - scene: '議論の論点を絞りたい場合'
      phrases:
        - '○○といった意見が挙げられましたが、これらをふまえて具体的な提案策を述べてください。'
        - '○○について良い点と悪い点を思いついた方は述べてください。'
    - scene: '意見の対立を解消したい場合'
      phrases:
        - '○○が議論の焦点になりそうですね。'
        - '○○という発言を考慮して意見に変わりのある方は述べてください。'
    - scene: 'デザイン案の説明が不十分な場合'
      phrases:
        - '○○についてもっと詳しく説明をお願いします。'
    - scene: '案の合成を促したい場合'
      phrases:
        - '◯◯を参考にした新しい案はありますか。'
    - scene: '案の発展を促したい場合'
      phrases:
        - 'デザイン案の可能性をお互い広げ合いましょう。'
- heading: '意見をまとめさせる'
  scenes:
    - scene: '多くの発言が出たので、意見をまとめたい場合'
      phrases:
        - '今までの意見をまとめてください'
    - scene: '結論を出したい場合'
      phrases:
        - '○○というコンセプトにみなさん賛成でよろしいですか？'
        - '○○という結論にみなさん賛成でよろしいですか？'
        - '○○の案を合意形成案にしたいと思います。'
