# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab7f1accea1afea2f7daf0a10e26563a32d26cadf7e9ebe362c0cd6ef31c9c546da62343434eaf1188e526cbbe33c9206120178d79498d7424e6c42c692af853

test:
  secret_key_base: 0bac90ca407a2b7de1c66781dd1cbc1e440f9336596228d5dedfbbc3871cf37e3e7f18397a3fa0679f051cc6c7f9cf9225728179d5ae0e0609c82549d54f57ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 658c7071bb31d2b99b24237752145eabdd1761c31919c469b236d54ebea8f4c728ee5d2c79184b790f4f40bb7b3500b1d0b24f799e5028b8a43b828fcfe76a36
