require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ThreadClassesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ThreadClass. As you add validations to ThreadClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ThreadClassesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all thread_classes as @thread_classes" do
      thread_class = ThreadClass.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:thread_classes)).to eq([thread_class])
    end
  end

  describe "GET show" do
    it "assigns the requested thread_class as @thread_class" do
      thread_class = ThreadClass.create! valid_attributes
      get :show, {:id => thread_class.to_param}, valid_session
      expect(assigns(:thread_class)).to eq(thread_class)
    end
  end

  describe "GET new" do
    it "assigns a new thread_class as @thread_class" do
      get :new, {}, valid_session
      expect(assigns(:thread_class)).to be_a_new(ThreadClass)
    end
  end

  describe "GET edit" do
    it "assigns the requested thread_class as @thread_class" do
      thread_class = ThreadClass.create! valid_attributes
      get :edit, {:id => thread_class.to_param}, valid_session
      expect(assigns(:thread_class)).to eq(thread_class)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ThreadClass" do
        expect {
          post :create, {:thread_class => valid_attributes}, valid_session
        }.to change(ThreadClass, :count).by(1)
      end

      it "assigns a newly created thread_class as @thread_class" do
        post :create, {:thread_class => valid_attributes}, valid_session
        expect(assigns(:thread_class)).to be_a(ThreadClass)
        expect(assigns(:thread_class)).to be_persisted
      end

      it "redirects to the created thread_class" do
        post :create, {:thread_class => valid_attributes}, valid_session
        expect(response).to redirect_to(ThreadClass.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved thread_class as @thread_class" do
        post :create, {:thread_class => invalid_attributes}, valid_session
        expect(assigns(:thread_class)).to be_a_new(ThreadClass)
      end

      it "re-renders the 'new' template" do
        post :create, {:thread_class => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested thread_class" do
        thread_class = ThreadClass.create! valid_attributes
        put :update, {:id => thread_class.to_param, :thread_class => new_attributes}, valid_session
        thread_class.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested thread_class as @thread_class" do
        thread_class = ThreadClass.create! valid_attributes
        put :update, {:id => thread_class.to_param, :thread_class => valid_attributes}, valid_session
        expect(assigns(:thread_class)).to eq(thread_class)
      end

      it "redirects to the thread_class" do
        thread_class = ThreadClass.create! valid_attributes
        put :update, {:id => thread_class.to_param, :thread_class => valid_attributes}, valid_session
        expect(response).to redirect_to(thread_class)
      end
    end

    describe "with invalid params" do
      it "assigns the thread_class as @thread_class" do
        thread_class = ThreadClass.create! valid_attributes
        put :update, {:id => thread_class.to_param, :thread_class => invalid_attributes}, valid_session
        expect(assigns(:thread_class)).to eq(thread_class)
      end

      it "re-renders the 'edit' template" do
        thread_class = ThreadClass.create! valid_attributes
        put :update, {:id => thread_class.to_param, :thread_class => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested thread_class" do
      thread_class = ThreadClass.create! valid_attributes
      expect {
        delete :destroy, {:id => thread_class.to_param}, valid_session
      }.to change(ThreadClass, :count).by(-1)
    end

    it "redirects to the thread_classes list" do
      thread_class = ThreadClass.create! valid_attributes
      delete :destroy, {:id => thread_class.to_param}, valid_session
      expect(response).to redirect_to(thread_classes_url)
    end
  end

end
